---
- name: Configure Central Router
  hosts: centralRouter
  become: true
  tasks:

    - name: Install | Network manager libs
      package:
        name:
          - NetworkManager-libnm
          - nm-connection-editor
          - libsemanage-python
          - policycoreutils-python
        state: present

    - name: Configure | Sysctl Forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Configure | Eth0
      nmcli:
        conn_name: "System eth0"
        type: ethernet
        ifname: eth0
        state: present

    - name: Configure | Eth1
      nmcli:
        conn_name: "System eth1"
        type: ethernet
        ifname: eth1
        gw4: 192.168.255.1
        state: present

    - name: Configure | Eth0 NoDefRoute
      shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0

    - name: Restart network service for interface eth0
      service:
        name: network
        state: restarted
