---
- name: Configure Central Router
  hosts: centralRouter
  become: true
  tasks:

    - name: Install | Network manager libs
      package:
        name:
          - NetworkManager-libnm
          - nm-connection-editor
          - libsemanage-python
          - policycoreutils-python
        state: present

    - name: Configure | Sysctl Forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Configure | Eth0
      community.general.nmcli:
        conn_name: "System eth0"
        type: ethernet
        ifname: eth0
        never_default4: yes
        state: present

    - name: Configure | Eth1
      community.general.nmcli:
        conn_name: "System eth1"
        type: ethernet
        ifname: eth1
        gw4: 192.168.255.1
        state: present

    - name: Configure | Eth5 to Office1
      community.general.nmcli:
        conn_name: "System eth5"
        ifname: eth5
        type: ethernet
        routes4: '192.168.2.0/26 192.168.254.2, 192.168.2.64/26 192.168.254.2, 192.168.2.128/26 192.168.254.2, 192.168.2.192/26 192.168.254.2'
        state: present

    - name: Configure | Eth6 to Office2
      community.general.nmcli:
        conn_name: "System eth6"
        ifname: eth6
        type: ethernet
        routes4: '192.168.1.0/25 192.168.253.2, 192.168.1.128/26 192.168.253.2, 192.168.1.192/26 192.168.253.2'
        state: present

    - name: Restart network service
      service:
        name: network
        state: restarted
